import { useEffect, useId, useRef } from 'react';

// Code-editor-styled textarea for the HTML body.
//
// Two layers, exact-pixel-aligned so they read as one element:
//   1. <pre> overlay with regex-highlighted HTML (the colors you see)
//   2. <textarea> on top with transparent text; only its caret + selection
//      paint. Typing happens here; the overlay re-renders from `value`.
//
// Long lines WRAP rather than horizontally scroll, because the typical
// serializer output is a single long string of HTML rows and horizontal
// scrolling is hostile UX for skimming. The overlay and textarea share the
// same wrap rules so the syntax-colored glyphs stay under the caret.
//
// Tab key inserts two spaces; Shift+Tab dedents the current line by up to
// two spaces. Both prevent the default focus-blur behavior.

const TAB = '  ';

export function CodeArea({ value, onChange, placeholder, ariaLabel, textareaRef: externalRef }) {
  const internalRef = useRef(null);
  // Caller can pass `textareaRef` to drive `insertAtCursor` from outside
  // (e.g., the Insert image / button / unsubscribe toolbar buttons in
  // TemplateEditor). If they don't, we use a local ref for scroll syncing.
  const textareaRef = externalRef || internalRef;
  const overlayRef = useRef(null);
  const id = useId();

  // Mirror the textarea's scroll position onto the overlay so the colored
  // markup stays under the caret as the user scrolls a tall document.
  useEffect(() => {
    const ta = textareaRef.current;
    if (!ta) return undefined;
    const onScroll = () => {
      if (overlayRef.current) {
        overlayRef.current.scrollTop = ta.scrollTop;
        overlayRef.current.scrollLeft = ta.scrollLeft;
      }
    };
    ta.addEventListener('scroll', onScroll);
    return () => ta.removeEventListener('scroll', onScroll);
    // textareaRef is a stable React ref; its identity doesn't change. Reading
    // .current at use time is correct. Empty dep array on purpose.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleKeyDown(event) {
    if (event.key !== 'Tab') return;
    event.preventDefault();
    const ta = event.currentTarget;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    const current = ta.value;

    if (event.shiftKey) {
      // Dedent the current line by up to TAB.length spaces.
      const lineStart = current.lastIndexOf('\n', start - 1) + 1;
      let removed = 0;
      while (removed < TAB.length && current[lineStart + removed] === ' ') removed += 1;
      if (!removed) return;
      const next = current.slice(0, lineStart) + current.slice(lineStart + removed);
      onChange(next);
      requestAnimationFrame(() => {
        ta.selectionStart = Math.max(lineStart, start - removed);
        ta.selectionEnd = Math.max(lineStart, end - removed);
      });
      return;
    }

    // Plain Tab: insert two spaces at the cursor.
    const next = current.slice(0, start) + TAB + current.slice(end);
    onChange(next);
    requestAnimationFrame(() => {
      ta.selectionStart = start + TAB.length;
      ta.selectionEnd = start + TAB.length;
    });
  }

  return (
    <div className="codearea">
      <pre className="codearea-overlay" aria-hidden="true" ref={overlayRef}>
        <code dangerouslySetInnerHTML={{ __html: highlight(value || '') + '\n' }} />
      </pre>
      <textarea
        id={id}
        className="codearea-input"
        ref={textareaRef}
        value={value || ''}
        onChange={(event) => onChange(event.target.value)}
        onKeyDown={handleKeyDown}
        placeholder={placeholder}
        aria-label={ariaLabel || 'HTML source'}
        spellCheck={false}
        autoCapitalize="off"
        autoCorrect="off"
        autoComplete="off"
      />
    </div>
  );
}

// HTML syntax highlighter. Two-phase approach:
//   1. Find every token (tag name, attr name, attr value, comment, merge
//      tag) and wrap it in a placeholder of the form  KIND:0  KIND:1 ...
//      The Unicode Private Use Area characters guarantee no collision with
//      legitimate HTML.
//   2. After every regex pass is done, swap each placeholder for its real
//      <span class="t-..."> markup.
//
// Why the indirection: a naive "insert spans inline" approach lets later
// regex passes accidentally match substrings of the spans the earlier
// passes inserted (e.g. the attribute-name regex matching `class=` inside
// `<span class="t-tag">`), which corrupts the rendered output. Tokenizing
// keeps each pass blind to the others.

// Private-Use-Area sentinel characters. Highly unlikely to appear in HTML
// authored by humans or generated by our serializer.
const SENT_OPEN = String.fromCharCode(0xE000);
const SENT_CLOSE = String.fromCharCode(0xE001);

const TOKEN_CLASS = {
  C: 't-comment',
  T: 't-tag',
  A: 't-attr',
  V: 't-string',
  M: 't-merge',
};

function tok(kind, payload) {
  return `${SENT_OPEN}${kind}${payload}${SENT_CLOSE}`;
}

function highlight(source) {
  const escaped = escapeHtml(source);

  // Pass 1: HTML comments. Tokenize so the tag-matching regex below skips
  // them entirely (the &lt;...&gt; shape would otherwise be a false match).
  let html = escaped.replace(/&lt;!--[\s\S]*?--&gt;/g, (match) => tok('C', match));

  // Pass 2: tags. Inside each matched tag, run a chain of inner replaces.
  // The outer regex uses negative lookahead `(?:(?!&gt;).)*?` instead of a
  // naive `[^&]*?`. `[^&]` would exclude `&` and stop matching at the first
  // HTML entity inside an attribute value (e.g. `&quot;`), which means
  // opening tags with quoted attributes never get highlighted at all. The
  // lookahead version stops only at a literal `&gt;` token.
  html = html.replace(/&lt;\/?[a-zA-Z](?:(?!&gt;)[\s\S])*?&gt;/g, (tag) => (
    tag
      // Tag name (first identifier after < or </).
      .replace(/(&lt;\/?)([a-zA-Z][a-zA-Z0-9-]*)/, (_m, lt, name) => `${lt}${tok('T', name)}`)
      // Attribute names. (?==) lookahead requires `=` to follow. Sentinels
      // never contain `=`, so they don't match here.
      .replace(/(\s)([a-zA-Z_][a-zA-Z0-9_-]*)(?==)/g, (_m, ws, attr) => `${ws}${tok('A', attr)}`)
      // Attribute values (double or single quoted, both already
      // HTML-escaped at this stage).
      .replace(/(=)(&quot;[^&]*?&quot;|&#39;[^&]*?&#39;)/g, (_m, eq, val) => `${eq}${tok('V', val)}`)
  ));

  // Pass 3: Mustache-style merge tags in the text body.
  html = html.replace(/\{\{\s*[a-zA-Z_][a-zA-Z0-9_]*\s*\}\}/g, (match) => tok('M', match));

  // Final pass: resolve every placeholder to <span class="..."> markup.
  const tokenRegex = new RegExp(
    `${SENT_OPEN}([CTAVM])([\\s\\S]*?)${SENT_CLOSE}`,
    'g',
  );
  return html.replace(tokenRegex, (_m, kind, payload) => (
    `<span class="${TOKEN_CLASS[kind]}">${payload}</span>`
  ));
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
